import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { fetchStats, Stat } from "../lib/stat";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
  const [stat, setStat] = useState<Stat | null>(null);
  useEffect(() => {
    fetchStats().then((newStat) => {
      setStat(newStat);
    });
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {stat !== null && <pre>{JSON.stringify(stat, null, 2)}</pre>}
      </main>
    </div>
  );
};

export default Home;
